return {
-- 	{
-- 		"epwalsh/obsidian.nvim",
-- 		version = "v3.9.0", -- recommended, use latest release instead of latest commit
-- 		dependencies = {
-- 			-- Required.
-- 			"nvim-lua/plenary.nvim",
-- 		},
-- 		opts = {
-- 			workspaces = {
-- 				{
-- 					name = "personal",
-- 					path = "/home/cheunn/Documents/notes",
-- 				},
-- 			},
-- 
-- 			daily_notes = {
-- 				-- Optional, if you keep daily notes in a separate directory.
-- 				folder = "daily-notes",
-- 				-- Optional, if you want to change the date format for the ID of daily notes.
-- 				date_format = "%Y-%m-%d",
-- 				-- Optional, if you want to change the date format of the default alias of daily notes.
-- 				alias_format = "%B %-d, %Y",
-- 				-- Optional, default tags to add to each new daily note created.
-- 				default_tags = { "daily-notes" },
-- 				-- Optional, if you want to automatically insert a template from your template directory like 'daily.md'
-- 				template = nil,
-- 			},
-- 			ui = {
-- 				enable = false, -- set to false to disable all additional syntax features
-- 			},
-- 
-- 			-- see below for full list of options 👇
-- 		},
-- 	},
}
