# import = ["nightfox.toml"]
import = ["custom.toml"]
# import = ["dracula.toml"]
live_config_reload = true

[font]
size = 12

[font.bold]
family = "Ubuntu Mono"

[font.bold_italic]
family = "Ubuntu Mono"

[font.italic]
family = "Ubuntu Mono"

[font.normal]
family = "Ubuntu Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[shell]
program = "/bin/fish"

[window]
opacity = 0.9

[window.padding]
#decoration = "none"
#dynamic_padding = true
x = 25
y = 25
