#!/bin/bash

if [ -z "$STOW_FOLDERS" ]; then
    STOW_FOLDERS="alacritty,fish,i3,rofi,picom,neofetch,steeple,nvim,personal,sxhkd,wallpapers,kitty,nitrogen"
fi

if [ -z "$DOTFILES" ]; then
    DOTFILES="$HOME/dotfiles"
fi

STOW_FOLDERS="$STOW_FOLDERS" DOTFILES="$DOTFILES" "$DOTFILES/install"
