- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  tags:
    - cli
  apt:
    name: docker-ce
    state: latest
    update_cache: true

      #- name: Install Docker Module for Python
      #  pip:
      #    name: docker

- name: Add Google Cloud public key
  tags:
    - kube
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repository
  tags:
    - kube
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Update apt cache again
  apt:
    update_cache: yes

- name: Install kubectl
  tags:
    - cli
    - kube
  apt:
    name: kubectl
    state: present

